### PR TITLE
Update API endpoint for Server-stats

### PR DESCRIPTION
**Pull request by Allram**
As of Immich v1.85.0 API endpoint for Server-stats is at /server-info/statistics and not /server-info/stats

### CODE REVIEW

**Comment by McGeaverBeaver** [comment]
Is this maintained? maybe we need to fork.. 

I have for now modified my own version of exporter.py and mapped a volume on my container.. yet that still is having issues...


{"asctime": "2023-11-13 16:42:24", "levelname": "INFO", "message": "Exporter is starting up"}
{"asctime": "2023-11-13 16:42:24", "levelname": "INFO", "message": "Found immich up and running at 192.168.10.230:8080."}
{"asctime": "2023-11-13 16:42:24", "levelname": "INFO", "message": "Attempting to connect"}
{"asctime": "2023-11-13 16:42:25", "levelname": "INFO", "message": "Exporter v1.0.6"}
{"asctime": "2023-11-13 16:42:25", "levelname": "INFO", "message": "Connected to immich successfully"}
{"asctime": "2023-11-13 16:42:25", "levelname": "ERROR", "message": "Is the Immich api token valid? Traceback:KeyError: 'usageByUser': "}
Traceback (most recent call last):
  File "/usr/bin/immich_exporter", line 33, in <module>
    sys.exit(load_entry_point('prometheus-immich-exporter==1.0.6', 'console_scripts', 'immich_exporter')())
  File "/usr/lib/python3.9/site-packages/immich_exporter/exporter.py", line 385, in main
    REGISTRY.register(ImmichMetricsCollector(config))
  File "/usr/lib/python3.9/site-packages/prometheus_client/registry.py", line 26, in register
    names = self._get_names(collector)
  File "/usr/lib/python3.9/site-packages/prometheus_client/registry.py", line 66, in _get_names
    for metric in desc_func():
  File "/usr/lib/python3.9/site-packages/immich_exporter/exporter.py", line 25, in collect
    metrics = self.get_immich_metrics()
  File "/usr/lib/python3.9/site-packages/immich_exporter/exporter.py", line 46, in get_immich_metrics
    metrics.extend(self.get_immich_users_stat)
  File "/usr/lib/python3.9/site-packages/immich_exporter/exporter.py", line 127, in get_immich_users_stat
    userData = response_user_stats.json()["usageByUser"]
KeyError: 'usageByUser'

** Press ANY KEY to close this window **

**Comment by Allram** [comment]
Maybe we all should work together on Marbabal's version? Since he also is a developer for Immich and responsible for the Unraid AIO Image?
https://github.com/martabal/immich-exporter

**Comment by friendlyFriend4000** [comment]
I still maintain it, but my reactions and replies are rather slow in the tech worldas I am not a software developer by trade, this time it  just happened that immich decided to make these changes while i was on vacation. 
I have the changed the api endpoint and added more useful error logs in another commit.

**Comment by McGeaverBeaver** [comment]
Thank you! I do prefer your dashboard 👍  thank you for the update, I have moved back to your version!

**Comment by friendlyFriend4000** [comment]
> Thank you! I do prefer your dashboard 👍 thank you for the update, I have moved back to your version!

Glad to hear there is still some interest!
As you may have noticed. Names have changed from first names to the full name. The reason for that is a deeper change in the API endpoint that I missed. I pushed yesterday's update too hastely. It's fixed in the 1.0.8 version. There are two sets of names unfortunately.

**Pull request closed without merging**
