### PR TITLE
Update dashboard-immich.json and some translations/naming

### PR DESCRIPTION
**Pull request by Allram**
- Update dashboard to default to select datasource at import and not default to a hardlocked ID on datasource.
- Updated Readme
- Added better description on UnRaid template
- Added Immich_api_token to readme
- Populated default Immich_port 8080 in Dockerfile
- Clarified that it's the Immich Proxy that you need to connect to, not Immich Server

### CODE REVIEW

**Comment by Allram** [comment]
More changes coming later tonight.

**Comment by Allram** [comment]
Should be good from my side now :)

**Comment by Allram** [comment]
Found some more bugs. Should be fine now.

**Comment by Allram** [comment]
Latest changes on the Dashboard for Grafana:

screencapture-grafana-fladby-org-d-ZWWp3aa4k-immich-2023-07-20-20_44_22

**Comment by friendlyFriend4000** [comment]
Sorry for such a late reply. I haven't noticed that there is a pull request and I hadn't thought that there will ever be one. I will observe my notifications better in the future so it won't happen again. There is gonna be time over the weekend for me to review it in depth. cheers.

**Comment by Allram** [comment]
No problem. I thought it was better to share my "improvements" than just keep them to myself.
Thanks for the great work on making this available 👌

**Comment by friendlyFriend4000** [comment]
loaded it up into my grafana instance and it looks all good. Originally I had the unorthodox idea of showing data, i guess going with the standard is a better idea for the general population. good work.

**Pull request merged**
